development: &default
  adapter: redis

test: *default

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: foreman_websocket_example_production
